name = "mrrrpack"
author = "musicalskele"
version = "0.2.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06f00fd9ba964062c13689fe8bc661f177bbb1204b40208e1864391f5fcecbf5"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
