name = "mrrrpack"
author = "musicalskele"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89b3ec702a3f057160ec7b05225a010f04ecec5363a48d5f784706f7445ab707"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
