name = "mrrrpack"
author = "musicalskele"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d55fe76b52f8d756d7e846fec0412a721f3407766bc0663ea0a9501db7928e2"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
