name = "mrrrpack"
author = "musicalskele"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80fe317237d2e3a4935a5a53fcef4ff9ae42f5e52234a5a2c332ef427e3f780b"

[versions]
fabric = "0.16.7"
minecraft = "1.21"
