name = "mrrrpack"
author = "musicalskele"
version = "0.2.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "524dc68d29764f00ead482213186175ad06d5d65a9ceec00611063263987aab9"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
