name = "mrrrpack"
author = "musicalskele"
version = "0.2.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "438d617c276267432551db11cc2f660cd3291dbe6ab087a44bcb201f4283fe27"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
