name = "mrrrpack"
author = "musicalskele"
version = "0.2.22"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b677640e98566c1f3b53103c887fbdaa7fb6ee9cfb8ac1c696579493ab27141b"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
