name = "mrrrpack"
author = "musicalskele"
version = "0.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a2bcb54108dc6882f9bfcd313beb2c8d221649eb933b635958e9de2a9cb7479"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"
