name = "mrrrpack"
author = "musicalskele"
version = "0.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b40a6ada8479ee953cf7c658edd7169202d7c0355c971eaeffc1c93029ff73ac"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
