name = "mrrrpack"
author = "musicalskele"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7c89ea9d562e34d50dc16916ab0602a448fd5abe96de2441588e9982fd032cb"

[versions]
fabric = "0.16.7"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
