name = "mrrrpack"
author = "musicalskele"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7f71f48b8a9cbb0de12e3929f213bebc5a0779f26ff05ccfcf63c6e3615d358"

[versions]
fabric = "0.16.7"
minecraft = "1.21"

[options]
acceptable-game-versions = ["1.21"]
