name = "mrrrpack"
author = "musicalskele"
version = "0.3.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "618a9e6e7dbd345411f663c81a5c10c2be967316d669a9581895b8c084a75fc5"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
