name = "mrrrpack"
author = "musicalskele"
version = "0.2.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3229d5451ac106e033917777d85fc1161b7badbc684941b53e24bb1d0e7669a"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
