name = "mrrrpack"
author = "musicalskele"
version = "0.2.19"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b1a73dcec3ab68b45956a4f8c014b218267fcb1c15680085f5b836752371b9b0"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
