name = "mrrrpack"
author = "musicalskele"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "835c6ead61256372d6ff68e8925520eb970413dd47f0051e5f69b406c00b09e2"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"
