name = "mrrrpack"
author = "musicalskele"
version = "0.2.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b03a5ab0507a9540752cfd4b2f1025ee4881f1f139566c6377bd824fcefad4f"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
