name = "mrrrpack"
author = "musicalskele"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2aaed1297ddc4adafc94c41158c96c530645f4456a78dca91caf8c422f46be4"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
