name = "mrrrpack"
author = "musicalskele"
version = "0.2.15"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44ba5cd44a58670e526232c459f6f89267d8b30a14b6c09e7f601fea6fbbec25"

[versions]
fabric = "0.16.8"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
